### ISSUE TITLE
Add method to retrieve offline channel mapping for WIB ethernet frames

### ISSUE THREAD

**Issue by adam-abed-abud** [DUNE-DAQ/detchannelmaps#34]
> The current method for retrieving the offline channel map `get_offline_channel_from_crate_slot_fiber_chan` ([link](https://github.com/DUNE-DAQ/detchannelmaps/blob/develop/plugins/PD2HDChannelMap.cpp#L33)) does not work for WIBEthernet frames. This is because there isn't anymore a value for `slot`, `crate` or `link` in WIBEth frame format

**Comment by wesketchum** [comment]
Done (in #35)
